### ISSUE TITLE
GPU environment

### ISSUE THREAD

**Issue by harrydeng8** [nusnlp/crosentgec#2]
Do we need to install Cuda, is version 10 works well with trainned model?

Thanks.

**Comment by harrydeng8** [comment]
Also, is the dictionary download in download_pretrained_crosent.sh?

Thanks!

**Comment by shamilcm** [comment]
The dictionaries are in `download.sh` script. The README file has been updated.

**Comment by harrydeng8** [comment]
it appear that models/embed/model.vec file is missing.  Could it be missed from the download.sh script?  Thanks!
