### ISSUE TITLE
Traning unable to detect GPU

### ISSUE THREAD

**Issue by pidugusundeep** [nusnlp/crosentgec#8]
Tried using p2.xlarge to run the training and it was not able to identify the GPU and always shows me can't run on the CPU machine, Even tried using the `$optionalgpu` and no luck 

![Screenshot 2020-03-23 at 12 50 43 PM](https://user-images.githubusercontent.com/10946649/77291780-ebb49a80-6d04-11ea-8eec-1204a6d9928d.png)

How do I get to fix this?

**Comment by shamilcm** [comment]
The problem has got to do with the machine/nvidia/cuda setup and does not seem to be a problem with the code as it trains on GPUs on my local machine without any issue.
